# Generated by Django 3.1 on 2021-11-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='abv',
            field=models.CharField(default=2, max_length=3),
            preserve_default=False,
        ),
    ]
